package pwr.PracaInz.Entities.Anime.Query.Parameters.Enums;

@SuppressWarnings("unused")
public enum Tags {
    Cunnilingus( 135, "Cunnilingus", "Features oral sex performed on female genitalia.", "Sexual Content", false, false, false),
    Otaku_Culture( 97, "Otaku Culture", "Centers around the culture of a fanatical fan-base.", "Theme-Other", false, false, false),
    Netorare( 124, "Netorare", "NTR; features a character with a partner shown being intimate with someone else.", "Sexual Content", false, false, false),
    Language_Barrier( 516, "Language Barrier", "A barrier to communication between people who are unable to speak a common language.", "Setting-Scene", false, false, false),
    Tomboy( 931, "Tomboy", "Features a girl who exhibits characteristics or behaviors considered in many cultures to be typical of boys.", "Cast-Traits", false, false, false),
    Villainess( 857, "Villainess", "Centers around or prominently features a villainous noble lady.", "Cast-Traits", false, false, false),
    Mafia( 107, "Mafia", "Centered around Italian organised crime syndicates.", "Theme-Other-Organisations", false, false, false),
    Slapstick( 83, "Slapstick", "Prominently features comedy based on deliberately clumsy actions or embarrassing events.", "Theme-Comedy", false, false, false),
    Cars( 10, "Cars", "Centers around the use of automotive vehicles.", "Theme-Other-Vehicle", false, false, false),
    Memory_Manipulation( 365, "Memory Manipulation", "Prominently features a character(s) who has had their memories altered.", "Theme-Other", false, false, false),
    Ojou_sama( 780, "Ojou-sama", "Features a wealthy, high-class, oftentimes stuck up and demanding female character.", "Cast-Traits", false, false, false),
    Boys_Love( 75, "Boys' Love", "Prominently features romance between two males, not inherently sexual.", "Theme-Romance", false, false, false),
    Martial_Arts( 30, "Martial Arts", "Centers around the use of traditional hand-to-hand combat.", "Theme-Action", false, false, false),
    Achronological_Order( 156, "Achronological Order", "Chapters or episodes do not occur in chronological order.", "Setting-Time", false, false, false),
    Age_Regression( 488, "Age Regression", "Prominently features a character who was returned to a younger state.", "Cast-Traits", false, false, false),
    Robots( 175, "Robots", "Prominently features humanoid machines.", "Cast-Traits", false, false, false),
    Steampunk( 95, "Steampunk", "Prominently features technology and designs inspired by 19th-century industrial steam-powered machinery.", "Theme-Fantasy", false, false, false),
    Yuri( 76, "Yuri", "Prominently features romance between two females, not inherently sexual. Also known as Girls' Love.", "Theme-Romance", false, false, false),
    Space( 63, "Space", "Partly or completely set in outer space.", "Setting-Universe", false, false, false),
    Love_Triangle( 139, "Love Triangle", "Centered around romantic feelings between more than two people. Includes all love polygons.", "Theme-Romance", false, false, false),
    Gambling( 91, "Gambling", "Centers around the act of gambling.", "Theme-Other", false, false, false),
    Feet( 631, "Feet", "Features the sexual depiction or stimulation of a character's feet.", "Sexual Content", false, false, false),
    Idol( 115, "Idol", "Centers around the life and activities of an idol.", "Cast-Traits", false, false, false),
    Gods( 253, "Gods", "Prominently features a character of divine or religious nature.", "Cast-Traits", false, false, false),
    Real_Robot( 160, "Real Robot", "Prominently features mechanical designs loosely influenced by real-world robotics.", "Theme-Sci-Fi-Mecha", false, false, false),
    Lacrosse( 437, "Lacrosse", "A team game played with a ball and lacrosse sticks.", "Theme-Game-Sport", false, false, false),
    Medicine( 659, "Medicine", "Centered around the activities of people working in the field of medicine.", "Theme-Other", false, false, false),
    Large_Breasts( 137, "Large Breasts", "Features a character with larger-than-average breasts.", "Sexual Content", false, false, false),
    Monster_Girl( 259, "Monster Girl", "Prominently features a female character who is part-monster.", "Cast-Traits", false, false, false),
    Triads( 214, "Triads", "Centered around Chinese organised crime syndicates.", "Theme-Other-Organisations", false, false, false),
    Asexual( 622, "Asexual", "Features a character who isn't romantically or sexually attracted to people of any sex or gender.", "Cast-Traits", false, false, false),
    Chimera( 774, "Chimera", "Features a beast made by combining animals, usually with humans", "Cast-Traits", false, false, false),
    Pirates( 201, "Pirates", "Prominently features sea-faring adventurers branded as criminals by the law.", "Cast-Traits", false, false, false),
    Wuxia( 303, "Wuxia", "Chinese fiction concerning the adventures of martial artists in Ancient China.", "Theme-Fantasy", false, false, false),
    Archery( 251, "Archery", "Centers around the sport of archery, or prominently features the use of archery in combat.", "Theme-Action", false, false, false),
    Drawing( 118, "Drawing", "Centers around the art of drawing, including manga and doujinshi.", "Theme-Arts", false, false, false),
    Defloration( 129, "Defloration", "Features a female character who has never had sexual relations (until now).", "Sexual Content", false, false, false),
    Nekomimi( 113, "Nekomimi", "Humanoid characters with cat-like features such as cat ears and a tail.", "Cast-Traits", false, false, false),
    POV( 215, "POV", "Point of View; features scenes shown from the perspective of the series protagonist.", "Technical", false, false, false),
    Age_Gap( 138, "Age Gap", "Prominently features romantic relations between people with a significant age difference.", "Theme-Romance", true, false, true),
    Super_Robot( 159, "Super Robot", "Prominently features large robots often piloted by hot-blooded protagonists.", "Theme-Sci-Fi-Mecha", false, false, false),
    Biographical( 239, "Biographical", "Based on true stories of real persons living or dead, written by another.", "Theme-Other", false, false, false),
    Crossdressing( 186, "Crossdressing", "Prominently features a character dressing up as the opposite sex.", "Cast-Traits", false, false, false),
    Mopeds( 176, "Mopeds", "Prominently features mopeds.", "Theme-Other-Vehicle", false, false, false),
    Twins( 494, "Twins", "Prominently features two or more siblings that were born at one birth.", "Cast-Traits", false, false, false),
    Urination( 180, "Urination", "Features one character urinating on another. Also know as a \"golden shower.\"", "Sexual Content", false, false, false),
    Yandere( 163, "Yandere", "Prominently features a character who is obsessively in love with another, to the point of acting deranged or violent.", "Cast-Traits", false, false, false),
    Urban_Fantasy( 321, "Urban Fantasy", "Set in a world similar to the real world, but with the existence of magic or other supernatural elements.", "Setting-Universe", false, false, false),
    Family_Life( 87, "Family Life", "Centers around the activities of a family unit.", "Theme-Slice of Life", false, false, false),
    Noir( 327, "Noir", "Stylized as a cynical crime drama with low-key visuals.", "Theme-Other", false, false, false),
    Revenge( 252, "Revenge", "Prominently features a character who aims to exact punishment in a resentful or vindictive manner.", "Theme-Drama", false, false, false),
    Seinen( 50, "Seinen", "Target demographic is adult males.", "Demographic", false, false, false),
    Video_Games( 308, "Video Games", "Centers around characters playing video games.", "Theme-Game", false, false, false),
    Stop_Motion( 323, "Stop Motion", "Animation style characterized by physical objects being moved incrementally between frames to create the illusion of movement.", "Technical", false, false, false),
    Full_CGI( 89, "Full CGI", "Almost entirely created with computer-generated imagery.", "Technical", false, false, false),
    Rimjob( 845, "Rimjob", "Features oral sex performed on the anus.", "Sexual Content", false, false, false),
    Body_Swapping( 154, "Body Swapping", "Centers around individuals swapping bodies with one another.", "Theme-Fantasy", true, false, true),
    Elf( 598, "Elf", "Prominently features a character who is an elf.", "Cast-Traits", false, false, false),
    Ero_Guro( 482, "Ero Guro", "Japanese literary and artistic movement originating in the 1930's. Works have a focus on grotesque eroticism, sexual corruption, and decadence.", "Theme-Other", false, false, false),
    Demons( 15, "Demons", "Prominently features malevolent otherworldly creatures.", "Cast-Traits", false, false, false),
    Tokusatsu( 513, "Tokusatsu", "Prominently features the elements, which resemble Japanese special effects live-action shows", "Theme-Sci-Fi", false, false, false),
    Post_Apocalyptic( 93, "Post-Apocalyptic", "Partly or completely set in a world or civilization after a global disaster.", "Setting-Universe", false, false, false),
    E_Sports( 792, "E-Sports", "Prominently features professional video game competitions, tournaments, players, etc.", "Theme-Game", false, false, false),
    Aliens( 191, "Aliens", "Prominently features extraterrestrial lifeforms.", "Cast-Traits", false, false, false),
    Chuunibyou( 267, "Chuunibyou", "Prominently features a character with \"Middle School 2nd Year Syndrome\", who either acts like a know-it-all adult or falsely believes they have special powers.", "Cast-Traits", false, false, false),
    Cannibalism( 870, "Cannibalism", "Prominently features the act of consuming another member of the same species as food.", "Theme-Other", false, false, false),
    Cyborg( 801, "Cyborg", "Prominently features a human character whose physiological functions are aided or enhanced by artificial means.", "Cast-Traits", false, false, false),
    Fugitive( 226, "Fugitive", "Prominently features a character evading capture by an individual or organization.", "Theme-Action", false, false, false),
    Cute_Girls_Doing_Cute_Things( 92, "Cute Girls Doing Cute Things", "Centers around, well, cute girls doing cute things.", "Theme-Slice of Life", false, false, false),
    Cosplay( 328, "Cosplay", "Features dressing up as a different character or profession.", "Cast-Traits", false, false, false),
    Harem( 23, "Harem", "Main cast features one male character plus several female characters who are romantically interested in him.", "Theme-Romance", false, false, false),
    Surfing( 678, "Surfing", "Centers around surfing as a sport.", "Theme-Game-Sport", false, false, false),
    Coming_of_Age( 102, "Coming of Age", "Centers around a character's transition from childhood to adulthood.", "Theme-Drama", false, false, false),
    Primarily_Male_Cast( 88, "Primarily Male Cast", "Main cast is mostly composed of male characters.", "Cast-Main Cast", false, false, false),
    Parody( 39, "Parody", "Features deliberate exaggeration of popular tropes or a particular genre to comedic effect.", "Theme-Comedy", false, false, false),
    Karuta( 182, "Karuta", "Centers around the game of karuta.", "Theme-Game-Card & Board Game", false, false, false),
    Zombie( 152, "Zombie", "Prominently features reanimated corpses which often prey on live humans and turn them into zombies.", "Cast-Traits", false, false, false),
    Animals( 433, "Animals", "Prominently features animal characters in a leading role.", "Theme-Other", false, false, false),
    Facial( 130, "Facial", "Features sexual ejaculation onto an individual's face.", "Sexual Content", false, false, false),
    Josei( 27, "Josei", "Target demographic is adult females.", "Demographic", false, false, false),
    Delinquents( 395, "Delinquents", "Features characters with a notorious image and attitude, sometimes referred to as \"yankees\".", "Cast-Traits", false, false, false),
    Food( 142, "Food", "Centers around cooking or food appraisal.", "Theme-Arts", false, false, false),
    Iyashikei( 81, "Iyashikei", "Primary aim is to heal the audience through serene depictions of characters' daily lives.", "Theme-Slice of Life", false, false, false),
    Youkai( 233, "Youkai", "Prominently features supernatural creatures from Japanese folklore.", "Theme-Fantasy", false, false, false),
    Butler( 812, "Butler", "Prominently features a character who is a butler.", "Cast-Traits", false, false, false),
    Fitness( 170, "Fitness", "Centers around exercise with the aim of improving physical health.", "Theme-Game-Sport", false, false, false),
    Boobjob( 126, "Boobjob", "Features the stimulation of male genitalia by breasts.", "Sexual Content", false, false, false),
    Rural( 250, "Rural", "Partly or completely set in the countryside.", "Setting-Scene", false, false, false),
    Asphyxiation( 651, "Asphyxiation", "Features breath play. ", "Sexual Content", false, false, false),
    Isekai( 244, "Isekai", "Features characters being transported into an alternate world setting and having to adapt to their new surroundings.", "Theme-Fantasy", false, false, false),
    Rape( 155, "Rape", "Features non-consensual sexual penetration.", "Sexual Content", false, false, false),
    Omegaverse( 533, "Omegaverse", "Alternative universe that prominently features dynamics modeled after wolves in which there are alphas, betas, and omegas and heat cycles as well as impregnation, regardless of gender.", "Setting-Universe", false, false, false),
    Denpa( 654, "Denpa", "Works that feature familiar characters acting in unfamiliar, yet seemingly orchestrated ways. Common iconography would include telephone poles and wires, building roof tops, suicides, disorientation, and paranoia. ", "Theme-Other", false, false, false),
    Magic( 29, "Magic", "Prominently features magical elements or the use of magic.", "Theme-Fantasy", false, false, false),
    Skeleton( 499, "Skeleton", "Prominently features skeleton(s) as a character.", "Cast-Traits", false, false, false),
    Foreign( 198, "Foreign", "Partly or completely set in a country outside of Japan.", "Setting-Scene", false, false, false),
    Photography( 195, "Photography", "Centers around the use of cameras to capture photos.", "Theme-Arts", false, false, false),
    Nudity( 100, "Nudity", "Features a character wearing no clothing or exposing intimate body parts.", "Cast-Traits", false, false, false),
    Classic_Literature( 227, "Classic Literature", "Discusses or adapts a work of classic world literature.", "Theme-Arts", false, false, false),
    Ice_Skating( 228, "Ice Skating", "Centers around the sport of ice skating.", "Theme-Game-Sport", false, false, false),
    Blackmail( 309, "Blackmail", "Features a character blackmailing another into performing sexual acts.", "Sexual Content", false, false, false),
    Dystopian( 217, "Dystopian", "Partly or completely set in a society characterized by poverty, squalor or oppression", "Setting-Time", false, false, false),
    Superhero( 172, "Superhero", "Prominently features super-powered humans who aim to serve the greater good.", "Theme-Fantasy", false, false, false),
    Space_Opera( 162, "Space Opera", "Centers around space warfare, advanced technology, chivalric romance and adventure.", "Theme-Sci-Fi", false, false, false),
    Puppetry( 325, "Puppetry", "Animation style involving the manipulation of puppets to act out scenes.", "Technical", false, false, false),
    Futanari( 188, "Futanari", "Features female characters with male genitalia.", "Sexual Content", false, false, false),
    Time_Manipulation( 96, "Time Manipulation", "Prominently features time-traveling or other time-warping phenomena.", "Theme-Sci-Fi", true, false, true),
    Aviation( 355, "Aviation", "Regarding the flying or operation of aircraft.", "Theme-Other-Vehicle", false, false, false),
    Crime( 648, "Crime", "Centers around unlawful activities punishable by the state or other authority.", "Theme-Other", false, false, false),
    Swimming( 150, "Swimming", "Centers around the sport of swimming.", "Theme-Game-Sport", false, false, false),
    Samurai( 291, "Samurai", "Prominently features warriors of medieval Japanese nobility bound by a code of honor.", "Cast-Traits", false, false, false),
    Tennis( 194, "Tennis", "Centers around the sport of tennis.", "Theme-Game-Sport", false, false, false),
    Cyberpunk( 108, "Cyberpunk", "Set in a future of advanced technological and scientific achievements that have resulted in social disorder.", "Theme-Sci-Fi", false, false, false),
    four_koma( 206, "4-koma", "A manga in the 'yonkoma' format, which consists of four equal-sized panels arranged in a vertical strip.", "Technical", false, false, false),
    Environmental( 342, "Environmental", "Concern with the state of the natural world and how humans interact with it.", "Theme-Other", false, false, false),
    Artificial_Intelligence( 517, "Artificial Intelligence", "Intelligent non-organic machines that work and react similarly to humans.", "Cast-Traits", false, false, false),
    Espionage( 310, "Espionage", "Prominently features characters infiltrating an organization in order to steal sensitive information.", "Theme-Action", false, false, false),
    Reverse_Harem( 123, "Reverse Harem", "Main cast features one female character plus several male characters who are romantically interested in her.", "Theme-Romance", false, false, false),
    Anti_Hero( 104, "Anti-Hero", "Features a protagonist who lacks conventional heroic attributes and may be considered a borderline villain.", "Cast-Main Cast", false, false, false),
    Acting( 548, "Acting", "Centers around actors or the acting industry.", "Theme-Arts", false, false, false),
    Episodic( 193, "Episodic", "Features story arcs that are loosely tied or lack an overarching plot.", "Technical", false, false, false),
    Fishing( 212, "Fishing", "Centers around the sport of fishing.", "Theme-Game-Sport", false, false, false),
    Lactation( 650, "Lactation", "Features breast milk play and production.", "Sexual Content", false, false, false),
    Surreal_Comedy( 281, "Surreal Comedy", "Prominently features comedic moments that defy casual reasoning, resulting in illogical events.", "Theme-Comedy", false, false, false),
    Gyaru( 356, "Gyaru", "Prominently features a female character who has a distinct American-emulated fashion style, such as tanned skin, bleached hair, and excessive makeup. Also known as gal.", "Cast-Traits", false, false, false),
    Ships( 305, "Ships", "Prominently features the use of sea-based transportation vessels.", "Theme-Other-Vehicle", false, false, false),
    Primarily_Child_Cast( 446, "Primarily Child Cast", "Main cast is mostly composed of characters below a high school age.", "Cast-Main Cast", false, false, false),
    Card_Battle( 178, "Card Battle", "Centers around individuals competing in card games.", "Theme-Game-Card & Board Game", false, false, false),
    Pregnant( 397, "Pregnant", "Features pregnant female characters in a sexual context.", "Sexual Content", false, false, false),
    Shoujo( 53, "Shoujo", "Target demographic is teenage and young adult females.", "Demographic", false, false, false),
    Mermaid( 558, "Mermaid", "A mythological creature with the body of a human and the tail of a fish", "Cast-Traits", false, false, false),
    Netorase( 280, "Netorase", "Features characters in a romantic relationship who agree to be sexually intimate with others.", "Sexual Content", false, false, false),
    Scuba_Diving( 811, "Scuba Diving", "Prominently features characters diving with the aid of special breathing equipment.", "Theme-Game-Sport", false, false, false),
    Athletics( 264, "Athletics", "Centers around sporting events that involve competitive running, jumping, throwing, or walking.", "Theme-Game-Sport", false, false, false),
    Group_Sex( 830, "Group Sex", "Features more than two participants engaged in sex simultaneously.", "Sexual Content", false, false, false),
    Tsundere( 164, "Tsundere", "Prominently features a character who acts cold and hostile in order to mask warmer emotions.", "Cast-Traits", false, false, false),
    Golf( 532, "Golf", "Centers around the sport of golf.", "Theme-Game-Sport", false, false, false),
    Police( 40, "Police", "Centers around the life and activities of law enforcement officers.", "Theme-Other-Organisations", false, false, false),
    Rakugo( 481, "Rakugo", "Rakugo is the traditional Japanese performance art of comic storytelling.", "Theme-Arts", false, false, false),
    Sex_Toys( 133, "Sex Toys", "Features objects that are designed to stimulate sexual pleasure.", "Sexual Content", false, false, false),
    Agender( 334, "Agender", "Prominently features agender characters.", "Cast-Traits", false, false, false),
    Yakuza( 199, "Yakuza", "Centered around Japanese organised crime syndicates.", "Theme-Other-Organisations", false, false, false),
    Anal_Sex( 185, "Anal Sex", "Features sexual penetration of the anal cavity.", "Sexual Content", false, false, false),
    Teens_Love( 649, "Teens' Love", "Sexually explicit love-story between individuals of the opposite sex, specifically targeting females of teens and young adult age.", "Theme-Romance", false, false, false),
    Bondage( 246, "Bondage", "Features BDSM, with or without the use of accessories.", "Sexual Content", false, false, false),
    Skateboarding( 809, "Skateboarding", "Centers around or prominently features skateboarding as a sport.", "Theme-Game-Sport", false, false, false),
    War( 111, "War", "Partly or completely set during wartime.", "Theme-Other", false, false, false),
    Go( 443, "Go", "Centered around the game of Go.", "Theme-Game-Card & Board Game", false, false, false),
    Ensemble_Cast( 105, "Ensemble Cast", "Features a large cast of characters with (almost) equal screen time and importance to the plot.", "Cast-Main Cast", false, false, false),
    Maids( 249, "Maids", "Prominently features a character who is a maid.", "Cast-Traits", false, false, false),
    Teacher( 165, "Teacher", "Protagonist is an educator, usually in a school setting.", "Cast-Traits", false, false, false),
    Terrorism( 285, "Terrorism", "Centers around the activities of a terrorist or terrorist organization.", "Theme-Other", false, false, false),
    Primarily_Female_Cast( 86, "Primarily Female Cast", "Main cast is mostly composed of female characters.", "Cast-Main Cast", false, false, false),
    Public_Sex( 127, "Public Sex", "Features sexual acts performed in public settings.", "Sexual Content", false, false, false),
    Outdoor( 262, "Outdoor", "Centers around hiking, camping or other outdoor activities.", "Setting-Scene", false, false, false),
    Mythology( 208, "Mythology", "Prominently features mythological elements, especially those from religious or cultural tradition.", "Theme-Fantasy", false, false, false),
    Survival( 143, "Survival", "Centers around the struggle to live in spite of extreme obstacles.", "Theme-Other", false, false, false),
    Tentacles( 189, "Tentacles", "Features the long appendages most commonly associated with octopuses or squid, often sexually penetrating a character.", "Sexual Content", false, false, false),
    Afterlife( 147, "Afterlife", "Partly or completely set in the afterlife.", "Setting-Universe", true, false, true),
    Ghost( 220, "Ghost", "Prominently features a character who is a ghost.", "Cast-Traits", false, false, false),
    CGI( 90, "CGI", "Prominently features scenes created with computer-generated imagery.", "Technical", false, false, false),
    Trains( 122, "Trains", "Prominently features trains.", "Theme-Other-Vehicle", false, false, false),
    Armpits( 629, "Armpits", "Features the sexual depiction or stimulation of a character's armpits.", "Sexual Content", false, false, false),
    Astronomy( 623, "Astronomy", "Relating or centered around the study of celestial objects and phenomena, space, or the universe.", "Theme-Other", false, false, false),
    Swordplay( 43, "Swordplay", "Prominently features the use of swords in combat.", "Theme-Action", false, false, false),
    Ashikoki( 315, "Ashikoki", "Footjob; features stimulation of genitalia by feet.", "Sexual Content", false, false, false),
    Military( 34, "Military", "Centered around the life and activities of military personnel.", "Theme-Other-Organisations", false, false, false),
    Kaiju( 276, "Kaiju", "Prominently features giant monsters.", "Theme-Fantasy", false, false, false),
    Tanks( 174, "Tanks", "Prominently features the use of tanks or other armoured vehicles.", "Theme-Other-Vehicle", false, false, false),
    Vampire( 74, "Vampire", "Prominently features a character who is a vampire.", "Cast-Traits", false, false, false),
    Gore( 94, "Gore", "Prominently features graphic bloodshed and violence.", "Theme-Other", false, false, false),
    Super_Power( 66, "Super Power", "Prominently features characters with special abilities that allow them to do what would normally be physically or logically impossible.", "Theme-Fantasy", false, false, false),
    Philosophy( 391, "Philosophy", "Relating or devoted to the study of the fundamental nature of knowledge, reality, and existence.", "Theme-Other", false, false, false),
    Werewolf( 534, "Werewolf", "Prominently features a character who is a werewolf.", "Cast-Traits", false, false, false),
    Body_Horror( 639, "Body Horror", "Features characters who undergo horrific transformations or disfigurement, often to their own detriment.", "Theme-Other", false, false, false),
    Human_Pet( 181, "Human Pet", "Features characters in a master-slave relationship where one is the \"owner\" and the other is a \"pet.\"", "Sexual Content", false, false, false),
    Ahegao( 279, "Ahegao", "Features a character making an exaggerated orgasm face.", "Sexual Content", false, false, false),
    Badminton( 235, "Badminton", "Centers around the sport of badminton.", "Theme-Game-Sport", false, false, false),
    Cosmic_Horror( 636, "Cosmic Horror", "A mediaType of horror that emphasizes human insignificance in the grand scope of cosmic reality; fearing the unknown and being powerless to fight it.", "Theme-Other", false, false, false),
    Educational( 140, "Educational", "Primary aim is to educate the audience.", "Theme-Other", false, false, false),
    Anthology( 471, "Anthology", "A collection of separate works collated into a single release.", "Technical", false, false, false),
    Historical( 25, "Historical", "Partly or completely set during a real period of world history.", "Setting-Time", false, false, false),
    Chibi( 324, "Chibi", "Features \"super deformed\" character designs with smaller, rounder proportions and a cute look.", "Theme-Other", false, false, false),
    Nun( 614, "Nun", "Prominently features a character who is a nun.", "Cast-Traits", false, false, false),
    Scat( 387, "Scat", "Lots of feces.", "Sexual Content", false, false, false),
    Amnesia( 240, "Amnesia", "Prominently features a character(s) with memory loss.", "Cast-Traits", false, false, false),
    Kemonomimi( 254, "Kemonomimi", "Prominently features humanoid characters with animal ears.", "Cast-Traits", false, false, false),
    Dragons( 224, "Dragons", "Prominently features mythical reptiles which generally have wings and can breathe fire.", "Cast-Traits", false, false, false),
    Shogi( 121, "Shogi", "Centers around the game of shogi.", "Theme-Game-Card & Board Game", false, false, false),
    Virtual_World( 112, "Virtual World", "Partly or completely set in the world inside a video game.", "Setting-Universe", false, false, false),
    Death_Game( 615, "Death Game", "Features characters participating in a game, where failure results in death.", "Theme-Other", false, false, false),
    Bullying( 171, "Bullying", "Prominently features the use of force for intimidation, often in a school setting.", "Theme-Drama", false, false, false),
    Cycling( 151, "Cycling", "Centers around the sport of cycling.", "Theme-Game-Sport", false, false, false),
    Henshin( 99, "Henshin", "Prominently features character or costume transformations which often grant special abilities.", "Theme-Fantasy", false, false, false),
    Gender_Bending( 77, "Gender Bending", "Prominently features a character who dresses and behaves in a way characteristic of another gender, or has been transformed into a person of another gender.", "Theme-Other", false, false, false),
    Prostitution( 190, "Prostitution", "Features characters who are paid for sexual favors.", "Sexual Content", false, false, false),
    Battle_Royale( 101, "Battle Royale", "Centers around a fierce group competition, often violent and with only one winner.", "Theme-Action", false, false, false),
    Exhibitionism( 901, "Exhibitionism", "Features the act of exposing oneself in public for sexual pleasure.", "Sexual Content", false, false, false),
    Circus( 476, "Circus", "Prominently features a circus.", "Setting-Scene", false, false, false),
    Lost_Civilization( 466, "Lost Civilization", "Featuring a civilization with few ruins or records that exist in present day knowledge.", "Theme-Other", false, false, false),
    Shounen( 56, "Shounen", "Target demographic is teenage and young adult males.", "Demographic", false, false, false),
    Hikikomori( 282, "Hikikomori", "Prominently features a character who withdraws from social life, often seeking extreme isolation.", "Cast-Traits", false, false, false),
    Ninja( 255, "Ninja", "Prominently features Japanese warriors traditionally trained in espionage, sabotage and assasination.", "Cast-Traits", false, false, false),
    Conspiracy( 456, "Conspiracy", "Contains one or more factions controlling or attempting to control the world from the shadows.", "Theme-Drama", false, false, false),
    Boxing( 169, "Boxing", "Centers around the sport of boxing.", "Theme-Game-Sport", false, false, false),
    Dinosaurs( 704, "Dinosaurs", "Prominently features Dinosaurs, prehistoric reptiles that went extinct millions of years ago.", "Cast-Traits", false, false, false),
    Work( 145, "Work", "Centers around the activities of a certain occupation.", "Setting-Scene", false, false, false),
    Sadism( 723, "Sadism", "Prominently features characters deriving pleasure, especially sexual gratification, from inflicting pain, suffering, or humiliation on others.", "Sexual Content", false, false, false),
    Netori( 316, "Netori", "Features a character shown being intimate with the partner of another character. The opposite of netorare.", "Sexual Content", false, false, false),
    Cheerleading( 646, "Cheerleading", "Centers around the activity of cheerleading. ", "Theme-Game-Sport", false, false, false),
    Time_Skip( 153, "Time Skip", "Features a gap in time used to advance the story.", "Setting-Time", true, false, true),
    College( 404, "College", "Partly or completely set in a college or university.", "Setting-Scene", false, false, false),
    Sweat( 630, "Sweat", "Lots of sweat. ", "Sexual Content", false, false, false),
    American_Football( 314, "American Football", "Centers around the sport of American football.", "Theme-Game-Sport", false, false, false),
    Pandemic( 874, "Pandemic", "Prominently features a disease prevalent over a whole country or the world.", "Theme-Other", false, false, false),
    Male_Protagonist( 82, "Male Protagonist", "Main character is male.", "Cast-Main Cast", false, false, false),
    Volleyball( 116, "Volleyball", "Centers around the sport of volleyball.", "Theme-Game-Sport", false, false, false),
    Musical( 265, "Musical", "Features a performance that combines songs, spoken dialogue, acting, and dance.", "Theme-Arts-Music", false, false, false),
    Motorcycles( 173, "Motorcycles", "Prominently features the use of motorcycles.", "Theme-Other-Vehicle", false, false, false),
    Threesome( 132, "Threesome", "Features sexual acts between three people.", "Sexual Content", false, false, false),
    Bar( 161, "Bar", "Partly or completely set in a bar.", "Setting-Scene", false, false, false),
    Full_Color( 207, "Full Color", "Manga fully colored or drawn in color.", "Technical", false, false, false),
    Shrine_Maiden( 468, "Shrine Maiden", "Prominently features a character who is a shrine maiden.", "Cast-Traits", false, false, false),
    Fashion( 410, "Fashion", "Centers around the fashion industry.", "Theme-Arts", false, false, false),
    Achromatic( 710, "Achromatic", "Contains animation that is primarily done in black and white", "Technical", false, false, false),
    Airsoft( 167, "Airsoft", "Centers around the sport of airsoft.", "Theme-Game-Sport", false, false, false),
    Baseball( 149, "Baseball", "Centers around the sport of baseball.", "Theme-Game-Sport", false, false, false),
    School_Club( 84, "School Club", "Partly or completely set in a school club scene.", "Setting-Scene", false, false, false),
    Software_Development( 386, "Software Development", "Centers around characters developing or programming a piece of technology, software, gaming, etc.", "Theme-Other", false, false, false),
    Table_Tennis( 120, "Table Tennis", "Centers around the sport of table tennis (also known as \"ping pong\").", "Theme-Game-Sport", false, false, false),
    Basketball( 192, "Basketball", "Centers around the sport of basketball.", "Theme-Game-Sport", false, false, false),
    No_Dialogue( 341, "No Dialogue", "This work contains no dialogue.", "Technical", false, false, false),
    Voyeur( 318, "Voyeur", "Features a character who enjoys seeing the sex acts or sex organs of others.", "Sexual Content", false, false, false),
    Centaur( 632, "Centaur", "Prominently features a character with a human upper body and the lower body of a horse.", "Cast-Traits", false, false, false),
    Dissociative_Identities( 536, "Dissociative Identities", "A case where one or more people share the same body.", "Cast-Traits", false, false, false),
    Nakadashi( 125, "Nakadashi", "Creampie; features sexual ejaculation inside of a character.", "Sexual Content", false, false, false),
    Dullahan( 658, "Dullahan", "Prominently features a character who is a Dullahan, a creature from Irish Folklore with a head that can be detached from its main body.", "Cast-Traits", false, false, false),
    Rehabilitation( 311, "Rehabilitation", "Prominently features the recovery of a character who became incapable of social life or work.", "Theme-Drama", false, false, false),
    Drugs( 489, "Drugs", "Prominently features the usage of drugs such as opioids, stimulants, hallucinogens etc.", "Theme-Other", false, false, false),
    Goblin( 480, "Goblin", "A goblin is a monstrous creature from European folklore. They are almost always small and grotesque, mischievous or outright malicious, and greedy. Sometimes with magical abilities.", "Cast-Traits", false, false, false),
    Advertisement( 505, "Advertisement", "Produced in order to promote the products of a certain company.", "Technical", false, false, false),
    Cult( 586, "Cult", "Features a social group with unorthodox religious, spiritual, or philosophical beliefs and practices.", "Theme-Other-Organisations", false, false, false),
    Writing( 394, "Writing", "Centers around the profession of writing books or novels.", "Theme-Arts", false, false, false),
    Succubus( 665, "Succubus", "Prominently features a character who is a succubus, a creature in medieval folklore that typically uses their sexual prowess to trap and seduce people to feed off them.", "Cast-Traits", false, false, false),
    Kuudere( 779, "Kuudere", "Prominently features a character who generally retains a cold, blunt and cynical exterior, but once one gets to know them, they have a very warm and loving interior.", "Cast-Traits", false, false, false),
    Office_Lady( 653, "Office Lady", "Prominently features a female office worker or OL.", "Cast-Traits", false, false, false),
    Assassins( 322, "Assassins", "Centers around characters who murder people as a profession.", "Theme-Other-Organisations", false, false, false),
    Tanned_Skin( 335, "Tanned Skin", "Prominently features characters with tanned skin.", "Cast-Traits", false, false, false),
    Kids( 28, "Kids", "Target demographic is young children.", "Demographic", false, false, false),
    School( 46, "School", "Partly or completely set in a primary or secondary educational institution.", "Setting-Scene", false, false, false),
    Satire( 80, "Satire", "Prominently features the use of comedy or ridicule to expose and criticise social phenomena.", "Theme-Comedy", false, false, false),
    Calligraphy( 204, "Calligraphy", "Centers around the art of calligraphy.", "Theme-Arts", false, false, false),
    LGBTQ_Themes( 483, "LGBTQ+ Themes", "Prominently features characters or themes associated with the LGBTQ+ community, such as sexuality or gender identity.", "Theme-Other", false, false, false),
    Dancing( 209, "Dancing", "Centers around the art of dance.", "Theme-Arts-Music", false, false, false),
    Parkour( 949, "Parkour", "Centers around the sport of parkour.", "Theme-Game-Sport", false, false, false),
    Politics( 103, "Politics", "Centers around politics, politicians, or government activities.", "Theme-Other", false, false, false),
    Handjob( 317, "Handjob", "Features the stimulation of genitalia by another's hands.", "Sexual Content", false, false, false),
    Vore( 624, "Vore", "Features a character being swallowed or swallowing another creature whole.", "Sexual Content", false, false, false),
    Slavery( 247, "Slavery", "Prominently features slaves, slavery, or slave trade.", "Theme-Other", false, false, false),
    Witch( 179, "Witch", "Prominently features a character who is a witch.", "Cast-Traits", false, false, false),
    Economics( 248, "Economics", "Centers around the field of economics.", "Theme-Other", false, false, false),
    Oiran( 593, "Oiran", "Prominently features a courtesan character of the Japanese Edo Period.", "Cast-Traits", false, false, false),
    Cultivation( 326, "Cultivation", "Features characters using training, often martial arts-related, and other special methods to cultivate life force and gain strength or immortality.", "Theme-Fantasy", false, false, false),
    Amputation( 652, "Amputation", "Features amputation or amputees.", "Sexual Content", false, false, false),
    Female_Protagonist( 98, "Female Protagonist", "Main character is female.", "Cast-Main Cast", false, false, false),
    Incest( 128, "Incest", "Features sexual relations between characters who are related by blood.", "Sexual Content", false, false, false),
    Flash( 242, "Flash", "Created using Flash animation techniques.", "Technical", false, false, false),
    Autobiographical( 519, "Autobiographical", "Real stories and anecdotes written by the author about their own life.", "Theme-Other", false, false, false),
    Crossover( 158, "Crossover", "Centers around the placement of two or more otherwise discrete fictional characters, settings, or universes into the context of a single story.", "Theme-Other", false, false, false),
    Virginity( 380, "Virginity", "Features a male character who has never had sexual relations (until now).", "Sexual Content", false, false, false),
    Tragedy( 85, "Tragedy", "Centers around tragic events and unhappy endings.", "Theme-Drama", true, false, true),
    Augmented_Reality( 364, "Augmented Reality", "Prominently features events with augmented reality as the main setting.", "Setting-Universe", false, false, false),
    Firefighters( 613, "Firefighters", "Centered around the life and activities of rescuers specialised in firefighting. ", "Theme-Other-Organisations", false, false, false),
    Wrestling( 231, "Wrestling", "Centers around the sport of wrestling.", "Theme-Game-Sport", false, false, false),
    Alternate_Universe( 146, "Alternate Universe", "Features multiple alternate universes in the same series.", "Setting-Universe", true, false, true),
    Reincarnation( 243, "Reincarnation", "Features a character being born again after death, typically as another person or in another world.", "Theme-Other", true, false, true),
    Football( 148, "Football", "Centers around the sport of football (known in the USA as \"soccer\").", "Theme-Game-Sport", false, false, false),
    Agriculture( 909, "Agriculture", "Prominently features agriculture practices.", "Theme-Slice of Life", false, false, false),
    Fellatio( 134, "Fellatio", "Blowjob; features oral sex performed on male genitalia.", "Sexual Content", false, false, false),
    Urban( 595, "Urban", "Partly or completely set in a city.", "Setting-Scene", false, false, false),
    Flat_Chest( 136, "Flat Chest", "Features a female character with smaller-than-average breasts.", "Sexual Content", false, false, false),
    Detective( 694, "Detective", "Features a character who investigates and solves crimes.", "Cast-Traits", false, false, false),
    Fairy_Tale( 400, "Fairy Tale", "This work tells a fairy tale, centers around fairy tales, or is based on a classic fairy tale.", "Theme-Fantasy", false, false, false),
    Bisexual( 294, "Bisexual", "Features a character who is romantically or sexually attracted to people of more than one sex or gender.", "Theme-Romance", false, false, false),
    Masturbation( 131, "Masturbation", "Features erotic stimulation of one's own genitalia or other erogenous regions.", "Sexual Content", false, false, false),
    Sumata( 360, "Sumata", "Pussyjob; features the stimulation of male genitalia by the thighs and labia majora of a female character.", "Sexual Content", false, false, false),
    Anachronism( 490, "Anachronism", "Prominently features elements that are out of place in the historical period the work takes place in, particularly modern elements in a historical setting.", "Setting-Time", false, false, false),
    Shapeshifting( 772, "Shapeshifting", "Features character(s) who changes one's appearance or form.", "Theme-Fantasy", false, false, false),
    Meta( 144, "Meta", "Features fourth wall-breaking references to itself or genre tropes.", "Theme-Other", false, false, false),
    Vikings( 618, "Vikings", "Prominently features Scandinavian seafaring pirates and warriors.", "Cast-Traits", false, false, false),
    Dungeon( 604, "Dungeon", "Prominently features a dungeon environment. ", "Setting-Scene", false, false, false),
    Gangs( 106, "Gangs", "Centers around gang organizations.", "Theme-Other-Organisations", false, false, false),
    Guns( 157, "Guns", "Prominently features the use of guns in combat.", "Theme-Action", false, false, false),
    Primarily_Adult_Cast( 109, "Primarily Adult Cast", "Main cast is mostly composed of characters above a high school age.", "Cast-Main Cast", false, false, false),
    Masochism( 999, "Masochism", "Prominently features characters who get sexual pleasure from being hurt or controlled by others.", "Sexual Content", false, false, false),
    Poker( 183, "Poker", "Centers around the game of poker or its variations.", "Theme-Game-Card & Board Game", false, false, false),
    Rugby( 221, "Rugby", "Centers around the sport of rugby.", "Theme-Game-Sport", false, false, false),
    MILF( 187, "MILF", "Features sexual intercourse with older women.", "Sexual Content", false, false, false),
    Band( 110, "Band", "Main cast is a group of musicians.", "Theme-Arts-Music", false, false, false),
    Mahjong( 117, "Mahjong", "Centered around the game of mahjong.", "Theme-Game-Card & Board Game", false, false, false),
    Rotoscoping( 683, "Rotoscoping", "Animation technique that animators use to trace over motion picture footage, frame by frame, to produce realistic action.", "Technical", false, false, false),
    Irrumatio( 359, "Irrumatio", "Oral rape; features a character thrusting their genitalia or a phallic object into the mouth of another character.", "Sexual Content", false, false, false),
    ;

    Tags(int id, String name, String description, String category, boolean isGeneralSpoiler, boolean isMediaSpoiler, boolean isAdult) {
    }
}
