version: '3'

#When doing changes here, remember to change testContainers in tests

services:
  mysql:
    image: mysql:8.0.26
    ports:
      - 3307:3306
    expose:
        - 3306
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/mysql_conf.sql:/docker-entrypoint-initdb.d/0_init.sql
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: RootPassword1
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloakUser
      MYSQL_PASSWORD: keycloakPassword1
    healthcheck:
        test: [ "CMD-SHELL", 'mysqladmin ping' ]
        interval: 10s
        timeout: 2s
        retries: 10

  keycloak:
    image: quay.io/keycloak/keycloak:15.0.0
    depends_on:
      - mysql
    ports:
      - 8180:8180
    restart: on-failure
    command:
      - "-Djboss.socket.binding.port-offset=100"
      - "-Dkeycloak.profile.feature.upload_scripts=enabled"
    volumes:
      - ./keycloak/realm:/opt/jboss/keycloak/imports
      - ./keycloak/scripts:/opt/jboss/startup-scripts/
    environment:
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloakUser
      DB_PASSWORD: keycloakPassword1
      #Should be used only on first startup
      #KEYCLOAK_USER: admin
      #KEYCLOAK_PASSWORD: Password1

  anime_app:
    build:
        context: ../
        dockerfile: Dockerfile
    depends_on:
        - mysql
        - keycloak
    ports:
        - 8080:8080
    restart: on-failure
    environment:
        SPRING_PORT: 8080
        ANILIST_API: https://graphql.anilist.co
        DATABASE_URL: mysql:3306
        KEYCLOAK_URL: keycloak:8180
        BACKEND_API_BASE_PATH: /api
        SERVE_STATIC_CONTENT: serve
    links:
        - mysql
        - keycloak

volumes:
  mysql: